### ISSUE TITLE
ARSCNViewDelegate not called

### ISSUE THREAD

**Issue by gdelafosse** [arirawr/FloorIsLava#1]
Hi
I cloned your project and ran it without change on my iPhone but the ARSCNViewDelegate  renderer methods are not called.
Do you know any issue with plane detections?

**Comment by arirawr** [comment]
@gdelafosse not that I know of - are you sure you're using a device running iOS 11 with an A9 chip or better?

**Comment by gdelafosse** [comment]
I found out that it depends a lot on the color of the floor. When it's dark, it doesn't work at all, even if the light is OK.

**Comment by arirawr** [comment]
Ah, makes sense. Going to go ahead and close this, as it seems like an Apple issue and not an issue with the repo.
